import { Injectable } from '@angular/core';

export type Lang = 'en' | 'es' | 'fr' | 'de';

const T: Record<Lang, Record<string, string>> = {
  en: {
    // Navigation
    nav_contacts: 'Home',
    nav_new_group: 'New Group',
    nav_requests: 'Requests',
    nav_profile: 'Profile',
    // Status
    status_title: 'MY STATUS',
    status_online: 'Online',
    status_away: 'Away',
    status_busy: 'Busy',
    status_offline: 'Offline',
    // Home
    home_search_contacts: 'Search contacts...',
    home_search_groups: 'Search groups...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Groups',
    home_promo_title: 'Start something new',
    home_promo_desc: 'Coordinate your weekend plans in a new group chat.',
    home_promo_btn: 'Create Group',
    home_my_groups: 'My groups',
    // Settings
    settings_title: 'Settings',
    settings_notifications: 'Notifications',
    settings_sound: 'Sound',
    settings_sound_sub: 'Play sound for incoming messages',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Haptic feedback on alerts',
    settings_appearance: 'Appearance',
    settings_theme: 'Theme',
    settings_theme_light: 'Light',
    settings_theme_dark: 'Dark',
    settings_language: 'Language',
    settings_language_desc: 'Choose your preferred language for the interface.',
    settings_edit_profile: 'Edit Profile',
    // Profile
    profile_title: 'Profile',
    profile_edit_title: 'Edit Profile',
    profile_full_name: 'Full Name',
    profile_username: 'Username',
    profile_status: 'Status',
    profile_change_photo: 'Change profile picture',
    profile_username_hint: 'Usernames are verified and cannot be changed.',
    profile_custom_status: 'CUSTOM STATUS',
    profile_set_status: 'Set a status…',
    profile_whats_status: "What's your status?",
    profile_your_name: 'Your name',
    profile_save: 'Save Changes',
    profile_logout: 'Log Out',
    // Chat
    chat_private_photo: 'Private photo',
    chat_image_seen: 'Image seen',
    chat_open_image: 'Open image',
    chat_image_deleted: 'Image deleted',
    chat_image: 'Image',
    chat_me: 'Me',
    chat_member: 'Member',
    chat_members: 'members',
    chat_caption: 'Add a caption...',
    chat_type: 'Type a message...',
    chat_image_count_one: 'image',
    chat_image_count_many: 'images',
    chat_is_writing: 'is writing...',
    chat_date_today: 'Today',
    chat_date_yesterday: 'Yesterday',
    chat_edit: 'Edit',
    chat_delete: 'Delete',
    chat_save: 'Save',
    chat_cancel: 'Cancel',
    chat_edited: 'edited',
    chat_msg_deleted: 'This message was deleted',
    buzz_toast: 'sent a buzz!',
    settings_buzz: 'Buzz',
    settings_buzz_sub: 'Classic Messenger buzz',
    settings_buzz_custom: 'Custom sound',
    settings_buzz_default: 'Default sound',
    notif_view: 'View',
    // Auth - shared
    auth_email_label: 'Email Address',
    auth_password_label: 'Password',
    auth_sign_in: 'Sign In',
    auth_back_signin: 'Back to sign in',
    // Auth - login
    auth_login_title: 'Welcome back',
    auth_remember_me: 'Remember me',
    auth_forgot_password: 'Forgot password?',
    auth_no_account: "Don't have an account?",
    auth_create_account: 'Create new account',
    // Auth - register
    auth_register_hero: 'Join the',
    auth_register_hero_accent: 'Playground.',
    auth_register_sub: 'Experience the warmth of early-2000s connection reimagined for the modern era.',
    auth_create_account_title: 'Create Account',
    auth_full_name: 'Full Name',
    auth_username: 'Username',
    auth_dob: 'Date of Birth',
    auth_confirm_password: 'Confirm Password',
    auth_register_btn: 'Register Account',
    auth_already_account: 'Already have an account?',
    // Auth - forgot password
    auth_recovery_tag: 'Account Recovery',
    auth_forgot_hero: 'Forgot your',
    auth_forgot_hero_accent: 'password?',
    auth_forgot_sub: "Enter your email and we'll send you a reset link.",
    auth_send_reset: 'Send Reset Link',
    auth_check_inbox: 'Check your inbox',
    auth_reset_sent_pre: 'We sent a reset link to',
    auth_reset_sent_post: 'Follow the link to set a new password.',
    auth_spam_hint: "Can't find it? Check your spam folder.",
    // Auth - reset password
    auth_security_tag: 'Security',
    auth_reset_hero: 'Set a new',
    auth_reset_hero_accent: 'password',
    auth_reset_sub: 'Enter and confirm your new password below.',
    auth_new_password_placeholder: 'New password',
    auth_confirm_password_placeholder: 'Confirm password',
    auth_save_password: 'Save New Password',
    auth_all_done: 'All done!',
    auth_password_updated: 'Your password has been updated. You can now sign in with your new credentials.',
    // Auth - validation errors
    auth_err_name_required: 'Name is required',
    auth_err_dob_required: 'Date of birth is required',
    auth_err_username_required: 'Username is required',
    auth_err_username_min: 'Minimum 3 characters',
    auth_err_email_required: 'Email is required',
    auth_err_email_invalid: 'Invalid email',
    auth_err_email_enter: 'Enter your email',
    auth_err_email_taken: 'This email is already registered',
    auth_err_password_required: 'Password is required',
    auth_err_password_min: 'Minimum 6 characters',
    auth_err_password_enter: 'Enter a password',
    auth_pwd_rule_length:  'At least 8 characters',
    auth_pwd_rule_upper:   'One uppercase letter (A–Z)',
    auth_pwd_rule_lower:   'One lowercase letter (a–z)',
    auth_pwd_rule_number:  'One number (0–9)',
    auth_pwd_rule_special: 'One special character (!@#$…)',
    auth_err_password_weak: 'Password does not meet all requirements',
    auth_err_confirm_required: 'Confirm your password',
    auth_err_passwords_mismatch: 'Passwords do not match',
    auth_err_generic: 'An error occurred. Please try again.',
    auth_err_link_expired: 'Error updating password. The link may have expired.',
    auth_strength_weak: 'Weak',
    auth_strength_medium: 'Medium',
    auth_strength_strong: 'Strong',
    // Detail pages
    detail_title: 'Details',
    detail_members: 'Members',
    detail_see_all: 'See All',
    detail_add: 'Add',
    detail_mute: 'Mute',
    detail_no_members: 'No members found',
    detail_danger_zone: 'Danger Zone',
    detail_leave_group: 'Leave Group',
    detail_leave_group_sub: 'Exit this community conversation',
    detail_audio: 'Audio',
    detail_video: 'Video',
    detail_privacy: 'Privacy & Preferences',
    detail_mute_notifications: 'Mute Notifications',
    detail_mute_sub: 'Silence messages from this contact',
    detail_shared_media: 'Shared Media',
    detail_shared_media_sub: 'Photos, videos and documents',
    detail_no_media: 'No shared media yet',
    detail_download: 'Download',
    detail_mg_today: 'Today',
    detail_mg_yesterday: 'Yesterday',
    detail_mg_this_week: 'This week',
    detail_mg_this_month: 'This month',
    detail_mg_this_year: 'This year',
    detail_mg_past_years: 'Older',
    detail_block: 'Block Contact',
    detail_block_sub: 'Prevent messages and calls',
    detail_block_confirm_msg: 'This user will no longer be able to find you or send you messages.',
    detail_block_done: 'Blocked',
    detail_delete_friendship: 'Delete Friendship',
    detail_delete_sub: 'Remove from your contact list',
    detail_delete_confirm_msg: 'This contact will be removed from both contact lists.',
    detail_delete_btn: 'Delete',
    detail_role_owner: 'Owner',
    detail_role_admin: 'Admin',
    detail_edit_group: 'Edit group',
    detail_edit_name_placeholder: 'Group name',
    detail_add_member: 'Add Member',
    detail_remove_member: 'Remove from group',
    detail_promote_admin: 'Promote to Admin',
    detail_demote_admin: 'Remove Admin role',
    detail_remove_confirm_title: 'Remove member?',
    detail_remove_confirm_msg: 'This member will be removed from the group.',
    detail_remove_btn: 'Remove',
    detail_leave_confirm_title: 'Leave Group?',
    detail_leave_confirm_msg: 'You will no longer have access to this group.',
    detail_leave_btn: 'Leave',
    detail_owner_leave_title: 'Transfer Ownership',
    detail_owner_leave_msg: 'Choose a member to become the new owner before leaving.',
    detail_transfer_btn: 'Transfer & Leave',
    detail_delete_group: 'Delete Group',
    detail_delete_group_sub: 'Permanently delete for everyone',
    detail_delete_group_title: 'Delete Group?',
    detail_delete_group_msg: 'This will permanently delete the group and all its messages. This cannot be undone.',
    detail_delete_group_btn: 'Delete Group',
    detail_no_friends_add: 'All your contacts are already in the group.',
    detail_save_changes: 'Save Changes',
    detail_group_image_label: 'GROUP AVATAR',
    detail_upload_image: 'Upload image',
    wb_title: 'Whiteboard',
    wb_clear_title: 'Clear whiteboard',
    wb_clear_msg: 'Delete all strokes? This cannot be undone.',
    wb_clear_btn: 'Clear',
    wb_pen: 'Pen',
    wb_eraser: 'Eraser',
    wb_opacity: 'Opacity',
    profile_blocked_title: 'Blocked Users',
    profile_blocked_count_one: 'blocked account',
    profile_blocked_count_many: 'blocked accounts',
    profile_blocked_empty: 'No blocked accounts',
    profile_blocked_search: 'Search by username...',
    profile_blocked_unblock: 'Unblock',
    // Create group
    create_group_title: 'New Group',
    create_group_tag: 'Build Your Circle',
    create_group_heading_pre: 'Create a',
    create_group_heading_accent: 'group',
    create_group_heading_post: 'chat',
    create_group_preview_placeholder: 'Group name…',
    create_group_preview_members_one: 'member selected',
    create_group_preview_members_many: 'members selected',
    create_group_preview_empty: 'No members yet',
    create_group_name_label: 'Group name',
    create_group_name_placeholder: 'Type a name…',
    create_group_color_label: 'Group color',
    create_group_members_label: 'Add members',
    create_group_loading: 'Loading contacts…',
    create_group_no_contacts: 'No contacts to add',
    create_group_btn: 'Create Group',
    create_group_error: 'Could not create group. Please try again.',
    // Requests
    req_title: 'Friend Requests',
    req_tag: 'New Connections',
    req_heading_pre: 'Who wants to',
    req_heading_accent: 'connect',
    req_heading_post: 'with you?',
    req_loading: 'Loading requests…',
    req_empty: 'No pending requests',
    req_accept: 'Accept',
    req_decline: 'Decline',
    // Add contact
    add_title: 'Add Contact',
    add_hero_pre: 'Find your',
    add_hero_accent: 'friends.',
    add_hero_sub: 'Search by username to start a new chat.',
    add_placeholder: 'Search by name or username',
    add_hint_title: 'Start typing to search',
    add_hint_sub: 'Type at least 2 characters to find users.',
    add_no_results: 'No users found for',
  },
  es: {
    nav_contacts: 'Inicio',
    nav_new_group: 'Nuevo Grupo',
    nav_requests: 'Solicitudes',
    nav_profile: 'Perfil',
    status_title: 'MI ESTADO',
    status_online: 'En línea',
    status_away: 'Ausente',
    status_busy: 'Ocupado',
    status_offline: 'Desconectado',
    home_search_contacts: 'Buscar contactos...',
    home_search_groups: 'Buscar grupos...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Grupos',
    home_promo_title: 'Empieza algo nuevo',
    home_promo_desc: 'Organiza los planes del fin de semana en un nuevo chat grupal.',
    home_promo_btn: 'Crear Grupo',
    home_my_groups: 'Mis grupos',
    settings_title: 'Ajustes',
    settings_notifications: 'Notificaciones',
    settings_sound: 'Sonido',
    settings_sound_sub: 'Reproducir sonido con mensajes entrantes',
    settings_vibration: 'Vibración',
    settings_vibration_sub: 'Vibración táctil en alertas',
    settings_appearance: 'Apariencia',
    settings_theme: 'Tema',
    settings_theme_light: 'Claro',
    settings_theme_dark: 'Oscuro',
    settings_language: 'Idioma',
    settings_language_desc: 'Elige tu idioma preferido para la interfaz.',
    settings_edit_profile: 'Editar Perfil',
    profile_title: 'Perfil',
    profile_edit_title: 'Editar Perfil',
    profile_full_name: 'Nombre Completo',
    profile_username: 'Usuario',
    profile_status: 'Estado',
    profile_change_photo: 'Cambiar foto de perfil',
    profile_username_hint: 'Los nombres de usuario son verificados y no se pueden cambiar.',
    profile_custom_status: 'ESTADO PERSONALIZADO',
    profile_set_status: 'Establece un estado…',
    profile_whats_status: '¿Cuál es tu estado?',
    profile_your_name: 'Tu nombre',
    profile_save: 'Guardar Cambios',
    profile_logout: 'Cerrar Sesión',
    chat_private_photo: 'Foto privada',
    chat_image_seen: 'Imagen vista',
    chat_open_image: 'Abrir imagen',
    chat_image_deleted: 'Imagen eliminada',
    chat_image: 'Imagen',
    chat_me: 'Yo',
    chat_member: 'Miembro',
    chat_members: 'miembros',
    chat_caption: 'Añade un pie de foto...',
    chat_type: 'Escribe un mensaje...',
    chat_image_count_one: 'imagen',
    chat_image_count_many: 'imágenes',
    chat_is_writing: 'está escribiendo...',
    chat_date_today: 'Hoy',
    chat_date_yesterday: 'Ayer',
    chat_edit: 'Editar',
    chat_delete: 'Eliminar',
    chat_save: 'Guardar',
    chat_cancel: 'Cancelar',
    chat_edited: 'editado',
    chat_msg_deleted: 'Este mensaje fue eliminado',
    buzz_toast: 'te ha enviado un zumbido!',
    settings_buzz: 'Buzz',
    settings_buzz_sub: 'Zumbido clásico de Messenger',
    settings_buzz_custom: 'Sonido personalizado',
    settings_buzz_default: 'Sonido predeterminado',
    notif_view: 'Ver',
    auth_email_label: 'Correo electrónico',
    auth_password_label: 'Contraseña',
    auth_sign_in: 'Iniciar sesión',
    auth_back_signin: 'Volver al inicio de sesión',
    auth_login_title: 'Bienvenido de nuevo',
    auth_remember_me: 'Recuérdame',
    auth_forgot_password: '¿Olvidaste tu contraseña?',
    auth_no_account: '¿No tienes cuenta?',
    auth_create_account: 'Crear nueva cuenta',
    auth_register_hero: 'Únete al',
    auth_register_hero_accent: 'Patio de juegos.',
    auth_register_sub: 'Experimenta la calidez de la conexión de principios de los 2000 reimaginada para la era moderna.',
    auth_create_account_title: 'Crear cuenta',
    auth_full_name: 'Nombre completo',
    auth_username: 'Usuario',
    auth_dob: 'Fecha de nacimiento',
    auth_confirm_password: 'Confirmar contraseña',
    auth_register_btn: 'Registrar cuenta',
    auth_already_account: '¿Ya tienes una cuenta?',
    auth_recovery_tag: 'Recuperación de cuenta',
    auth_forgot_hero: '¿Olvidaste tu',
    auth_forgot_hero_accent: 'contraseña?',
    auth_forgot_sub: 'Introduce tu correo y te enviaremos un enlace de restablecimiento.',
    auth_send_reset: 'Enviar enlace',
    auth_check_inbox: 'Revisa tu bandeja de entrada',
    auth_reset_sent_pre: 'Enviamos un enlace de restablecimiento a',
    auth_reset_sent_post: 'Sigue el enlace para establecer una nueva contraseña.',
    auth_spam_hint: '¿No lo encuentras? Revisa tu carpeta de spam.',
    auth_security_tag: 'Seguridad',
    auth_reset_hero: 'Establece una nueva',
    auth_reset_hero_accent: 'contraseña',
    auth_reset_sub: 'Introduce y confirma tu nueva contraseña.',
    auth_new_password_placeholder: 'Nueva contraseña',
    auth_confirm_password_placeholder: 'Confirmar contraseña',
    auth_save_password: 'Guardar nueva contraseña',
    auth_all_done: '¡Listo!',
    auth_password_updated: 'Tu contraseña ha sido actualizada. Ya puedes iniciar sesión con tus nuevas credenciales.',
    auth_err_name_required: 'El nombre es obligatorio',
    auth_err_dob_required: 'La fecha de nacimiento es obligatoria',
    auth_err_username_required: 'El nombre de usuario es obligatorio',
    auth_err_username_min: 'Mínimo 3 caracteres',
    auth_err_email_required: 'El correo es obligatorio',
    auth_err_email_invalid: 'Correo no válido',
    auth_err_email_enter: 'Introduce tu correo',
    auth_err_email_taken: 'Este correo ya está registrado',
    auth_err_password_required: 'La contraseña es obligatoria',
    auth_err_password_min: 'Mínimo 6 caracteres',
    auth_err_password_enter: 'Introduce una contraseña',
    auth_pwd_rule_length:  'Mínimo 8 caracteres',
    auth_pwd_rule_upper:   'Una mayúscula (A–Z)',
    auth_pwd_rule_lower:   'Una minúscula (a–z)',
    auth_pwd_rule_number:  'Un número (0–9)',
    auth_pwd_rule_special: 'Un carácter especial (!@#$…)',
    auth_err_password_weak: 'La contraseña no cumple todos los requisitos',
    auth_err_confirm_required: 'Confirma tu contraseña',
    auth_err_passwords_mismatch: 'Las contraseñas no coinciden',
    auth_err_generic: 'Ocurrió un error. Inténtalo de nuevo.',
    auth_err_link_expired: 'Error al actualizar la contraseña. El enlace puede haber expirado.',
    auth_strength_weak: 'Débil',
    auth_strength_medium: 'Regular',
    auth_strength_strong: 'Fuerte',
    detail_title: 'Detalles',
    detail_members: 'Miembros',
    detail_see_all: 'Ver todos',
    detail_add: 'Añadir',
    detail_mute: 'Silenciar',
    detail_no_members: 'No se encontraron miembros',
    detail_danger_zone: 'Zona de peligro',
    detail_leave_group: 'Salir del grupo',
    detail_leave_group_sub: 'Abandonar esta conversación',
    detail_audio: 'Audio',
    detail_video: 'Vídeo',
    detail_privacy: 'Privacidad y Preferencias',
    detail_mute_notifications: 'Silenciar notificaciones',
    detail_mute_sub: 'Silenciar mensajes de este contacto',
    detail_shared_media: 'Medios compartidos',
    detail_shared_media_sub: 'Fotos, vídeos y documentos',
    detail_no_media: 'Aún no hay medios compartidos',
    detail_download: 'Descargar',
    detail_mg_today: 'Hoy',
    detail_mg_yesterday: 'Ayer',
    detail_mg_this_week: 'Esta semana',
    detail_mg_this_month: 'Este mes',
    detail_mg_this_year: 'Este año',
    detail_mg_past_years: 'Años anteriores',
    detail_block: 'Bloquear contacto',
    detail_block_sub: 'Evitar mensajes y llamadas',
    detail_block_confirm_msg: 'Este usuario ya no podrá encontrarte ni enviarte mensajes.',
    detail_block_done: 'Bloqueado',
    detail_delete_friendship: 'Eliminar amistad',
    detail_delete_sub: 'Eliminar de tu lista de contactos',
    detail_delete_confirm_msg: 'Este contacto se eliminará de ambas listas de contactos.',
    detail_delete_btn: 'Eliminar',
    detail_role_owner: 'Dueño',
    detail_role_admin: 'Admin',
    detail_edit_group: 'Editar grupo',
    detail_edit_name_placeholder: 'Nombre del grupo',
    detail_add_member: 'Añadir miembro',
    detail_remove_member: 'Expulsar del grupo',
    detail_promote_admin: 'Promover a Admin',
    detail_demote_admin: 'Quitar rol Admin',
    detail_remove_confirm_title: '¿Expulsar miembro?',
    detail_remove_confirm_msg: 'Este miembro será eliminado del grupo.',
    detail_remove_btn: 'Expulsar',
    detail_leave_confirm_title: '¿Salir del grupo?',
    detail_leave_confirm_msg: 'Ya no tendrás acceso a este grupo.',
    detail_leave_btn: 'Salir',
    detail_owner_leave_title: 'Transferir propiedad',
    detail_owner_leave_msg: 'Elige un miembro para que sea el nuevo dueño antes de salir.',
    detail_transfer_btn: 'Transferir y salir',
    detail_delete_group: 'Eliminar grupo',
    detail_delete_group_sub: 'Eliminar permanentemente para todos',
    detail_delete_group_title: '¿Eliminar grupo?',
    detail_delete_group_msg: 'Esto eliminará permanentemente el grupo y todos sus mensajes. No se puede deshacer.',
    detail_delete_group_btn: 'Eliminar grupo',
    detail_no_friends_add: 'Todos tus contactos ya están en el grupo.',
    detail_save_changes: 'Guardar cambios',
    detail_group_image_label: 'IMAGEN DEL GRUPO',
    detail_upload_image: 'Subir imagen',
    wb_title: 'Pizarra',
    wb_clear_title: 'Limpiar pizarra',
    wb_clear_msg: '¿Borrar todos los trazos? Esta acción no se puede deshacer.',
    wb_clear_btn: 'Limpiar',
    wb_pen: 'Lápiz',
    wb_eraser: 'Borrador',
    wb_opacity: 'Opacidad',
    profile_blocked_title: 'Usuarios bloqueados',
    profile_blocked_count_one: 'cuenta bloqueada',
    profile_blocked_count_many: 'cuentas bloqueadas',
    profile_blocked_empty: 'No hay cuentas bloqueadas',
    profile_blocked_search: 'Buscar por nombre de usuario...',
    profile_blocked_unblock: 'Desbloquear',
    create_group_title: 'Nuevo Grupo',
    create_group_tag: 'Construye tu Círculo',
    create_group_heading_pre: 'Crea un',
    create_group_heading_accent: 'grupo',
    create_group_heading_post: 'de chat',
    create_group_preview_placeholder: 'Nombre del grupo…',
    create_group_preview_members_one: 'miembro seleccionado',
    create_group_preview_members_many: 'miembros seleccionados',
    create_group_preview_empty: 'Sin miembros aún',
    create_group_name_label: 'Nombre del grupo',
    create_group_name_placeholder: 'Escribe un nombre…',
    create_group_color_label: 'Color del grupo',
    create_group_members_label: 'Añadir miembros',
    create_group_loading: 'Cargando contactos…',
    create_group_no_contacts: 'No hay contactos para añadir',
    create_group_btn: 'Crear Grupo',
    create_group_error: 'No se pudo crear el grupo. Inténtalo de nuevo.',
    req_title: 'Solicitudes de Amistad',
    req_tag: 'Nuevas Conexiones',
    req_heading_pre: '¿Quién quiere',
    req_heading_accent: 'conectar',
    req_heading_post: 'contigo?',
    req_loading: 'Cargando solicitudes…',
    req_empty: 'No hay solicitudes pendientes',
    req_accept: 'Aceptar',
    req_decline: 'Rechazar',
    add_title: 'Añadir Contacto',
    add_hero_pre: 'Encuentra a tus',
    add_hero_accent: 'amigos.',
    add_hero_sub: 'Busca por nombre de usuario para iniciar un chat.',
    add_placeholder: 'Buscar por nombre o usuario',
    add_hint_title: 'Empieza a escribir para buscar',
    add_hint_sub: 'Escribe al menos 2 caracteres para encontrar usuarios.',
    add_no_results: 'No se encontraron usuarios para',
  },
  fr: {
    nav_contacts: 'Accueil',
    nav_new_group: 'Nouveau Groupe',
    nav_requests: 'Demandes',
    nav_profile: 'Profil',
    status_title: 'MON STATUT',
    status_online: 'En ligne',
    status_away: 'Absent',
    status_busy: 'Occupé',
    status_offline: 'Hors ligne',
    home_search_contacts: 'Rechercher des contacts...',
    home_search_groups: 'Rechercher des groupes...',
    home_tab_chats: 'Discussions',
    home_tab_groups: 'Groupes',
    home_promo_title: 'Commencez quelque chose',
    home_promo_desc: 'Organisez vos plans de week-end dans un nouveau chat de groupe.',
    home_promo_btn: 'Créer un Groupe',
    home_my_groups: 'Mes groupes',
    settings_title: 'Paramètres',
    settings_notifications: 'Notifications',
    settings_sound: 'Son',
    settings_sound_sub: 'Jouer un son pour les messages entrants',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Retour haptique sur les alertes',
    settings_appearance: 'Apparence',
    settings_theme: 'Thème',
    settings_theme_light: 'Clair',
    settings_theme_dark: 'Sombre',
    settings_language: 'Langue',
    settings_language_desc: "Choisissez votre langue préférée pour l'interface.",
    settings_edit_profile: 'Modifier le Profil',
    profile_title: 'Profil',
    profile_edit_title: 'Modifier le Profil',
    profile_full_name: 'Nom Complet',
    profile_username: "Nom d'utilisateur",
    profile_status: 'Statut',
    profile_change_photo: 'Changer la photo de profil',
    profile_username_hint: "Les noms d'utilisateur sont vérifiés et ne peuvent pas être modifiés.",
    profile_custom_status: 'STATUT PERSONNALISÉ',
    profile_set_status: 'Définir un statut…',
    profile_whats_status: 'Quel est votre statut?',
    profile_your_name: 'Votre nom',
    profile_save: 'Enregistrer',
    profile_logout: 'Se Déconnecter',
    chat_private_photo: 'Photo privée',
    chat_image_seen: 'Image vue',
    chat_open_image: "Ouvrir l'image",
    chat_image_deleted: 'Image supprimée',
    chat_image: 'Image',
    chat_me: 'Moi',
    chat_member: 'Membre',
    chat_members: 'membres',
    chat_caption: 'Ajouter une légende...',
    chat_type: 'Tapez un message...',
    chat_image_count_one: 'image',
    chat_image_count_many: 'images',
    chat_is_writing: 'est en train d\'écrire...',
    chat_date_today: "Aujourd'hui",
    chat_date_yesterday: 'Hier',
    chat_edit: 'Modifier',
    chat_delete: 'Supprimer',
    chat_save: 'Enregistrer',
    chat_cancel: 'Annuler',
    chat_edited: 'modifié',
    chat_msg_deleted: 'Ce message a été supprimé',
    buzz_toast: 'vous a buzzé !',
    settings_buzz: 'Buzz',
    settings_buzz_sub: 'Buzz classique Messenger',
    settings_buzz_custom: 'Son personnalisé',
    settings_buzz_default: 'Son par défaut',
    notif_view: 'Voir',
    auth_email_label: 'Adresse e-mail',
    auth_password_label: 'Mot de passe',
    auth_sign_in: 'Se connecter',
    auth_back_signin: 'Retour à la connexion',
    auth_login_title: 'Bon retour',
    auth_remember_me: 'Se souvenir de moi',
    auth_forgot_password: 'Mot de passe oublié ?',
    auth_no_account: "Vous n'avez pas de compte ?",
    auth_create_account: 'Créer un nouveau compte',
    auth_register_hero: 'Rejoignez le',
    auth_register_hero_accent: 'Terrain de jeu.',
    auth_register_sub: "Découvrez la chaleur de la connexion du début des années 2000 réimaginée pour l'ère moderne.",
    auth_create_account_title: 'Créer un compte',
    auth_full_name: 'Nom complet',
    auth_username: "Nom d'utilisateur",
    auth_dob: 'Date de naissance',
    auth_confirm_password: 'Confirmer le mot de passe',
    auth_register_btn: 'Créer le compte',
    auth_already_account: 'Vous avez déjà un compte ?',
    auth_recovery_tag: 'Récupération de compte',
    auth_forgot_hero: 'Mot de passe',
    auth_forgot_hero_accent: 'oublié ?',
    auth_forgot_sub: 'Entrez votre e-mail et nous vous enverrons un lien de réinitialisation.',
    auth_send_reset: 'Envoyer le lien',
    auth_check_inbox: 'Vérifiez votre boîte mail',
    auth_reset_sent_pre: 'Nous avons envoyé un lien à',
    auth_reset_sent_post: 'Suivez le lien pour définir un nouveau mot de passe.',
    auth_spam_hint: 'Vous ne le trouvez pas ? Vérifiez vos spams.',
    auth_security_tag: 'Sécurité',
    auth_reset_hero: 'Définir un nouveau',
    auth_reset_hero_accent: 'mot de passe',
    auth_reset_sub: 'Entrez et confirmez votre nouveau mot de passe.',
    auth_new_password_placeholder: 'Nouveau mot de passe',
    auth_confirm_password_placeholder: 'Confirmer le mot de passe',
    auth_save_password: 'Enregistrer le mot de passe',
    auth_all_done: 'Terminé !',
    auth_password_updated: 'Votre mot de passe a été mis à jour. Vous pouvez maintenant vous connecter avec vos nouveaux identifiants.',
    auth_err_name_required: 'Le nom est obligatoire',
    auth_err_dob_required: 'La date de naissance est obligatoire',
    auth_err_username_required: "Le nom d'utilisateur est obligatoire",
    auth_err_username_min: 'Minimum 3 caractères',
    auth_err_email_required: "L'e-mail est obligatoire",
    auth_err_email_invalid: 'E-mail invalide',
    auth_err_email_enter: 'Entrez votre e-mail',
    auth_err_email_taken: 'Cet e-mail est déjà enregistré',
    auth_err_password_required: 'Le mot de passe est obligatoire',
    auth_err_password_min: 'Minimum 6 caractères',
    auth_err_password_enter: 'Entrez un mot de passe',
    auth_pwd_rule_length:  'Au moins 8 caractères',
    auth_pwd_rule_upper:   'Une majuscule (A–Z)',
    auth_pwd_rule_lower:   'Une minuscule (a–z)',
    auth_pwd_rule_number:  'Un chiffre (0–9)',
    auth_pwd_rule_special: 'Un caractère spécial (!@#$…)',
    auth_err_password_weak: 'Le mot de passe ne répond pas à tous les critères',
    auth_err_confirm_required: 'Confirmez votre mot de passe',
    auth_err_passwords_mismatch: 'Les mots de passe ne correspondent pas',
    auth_err_generic: 'Une erreur est survenue. Veuillez réessayer.',
    auth_err_link_expired: 'Erreur de mise à jour. Le lien a peut-être expiré.',
    auth_strength_weak: 'Faible',
    auth_strength_medium: 'Moyen',
    auth_strength_strong: 'Fort',
    detail_title: 'Détails',
    detail_members: 'Membres',
    detail_see_all: 'Voir tout',
    detail_add: 'Ajouter',
    detail_mute: 'Muet',
    detail_no_members: 'Aucun membre trouvé',
    detail_danger_zone: 'Zone dangereuse',
    detail_leave_group: 'Quitter le groupe',
    detail_leave_group_sub: 'Quitter cette conversation',
    detail_audio: 'Audio',
    detail_video: 'Vidéo',
    detail_privacy: 'Confidentialité & Préférences',
    detail_mute_notifications: 'Désactiver les notifications',
    detail_mute_sub: 'Masquer les messages de ce contact',
    detail_shared_media: 'Médias partagés',
    detail_shared_media_sub: 'Photos, vidéos et documents',
    detail_no_media: 'Aucun média partagé pour l\'instant',
    detail_download: 'Télécharger',
    detail_mg_today: 'Aujourd\'hui',
    detail_mg_yesterday: 'Hier',
    detail_mg_this_week: 'Cette semaine',
    detail_mg_this_month: 'Ce mois-ci',
    detail_mg_this_year: 'Cette année',
    detail_mg_past_years: 'Plus ancien',
    detail_block: 'Bloquer le contact',
    detail_block_sub: 'Empêcher les messages et appels',
    detail_block_confirm_msg: "Cet utilisateur ne pourra plus vous trouver ni vous envoyer de messages.",
    detail_block_done: 'Bloqué',
    detail_delete_friendship: 'Supprimer l\'amitié',
    detail_delete_sub: 'Retirer de votre liste de contacts',
    detail_delete_confirm_msg: 'Ce contact sera supprimé des deux listes de contacts.',
    detail_delete_btn: 'Supprimer',
    detail_role_owner: 'Propriétaire',
    detail_role_admin: 'Admin',
    detail_edit_group: 'Modifier le groupe',
    detail_edit_name_placeholder: 'Nom du groupe',
    detail_add_member: 'Ajouter un membre',
    detail_remove_member: 'Retirer du groupe',
    detail_promote_admin: 'Promouvoir en Admin',
    detail_demote_admin: 'Retirer le rôle Admin',
    detail_remove_confirm_title: 'Retirer le membre ?',
    detail_remove_confirm_msg: 'Ce membre sera retiré du groupe.',
    detail_remove_btn: 'Retirer',
    detail_leave_confirm_title: 'Quitter le groupe ?',
    detail_leave_confirm_msg: "Vous n'aurez plus accès à ce groupe.",
    detail_leave_btn: 'Quitter',
    detail_owner_leave_title: 'Transférer la propriété',
    detail_owner_leave_msg: 'Choisissez un membre pour devenir le nouveau propriétaire avant de partir.',
    detail_transfer_btn: 'Transférer et partir',
    detail_delete_group: 'Supprimer le groupe',
    detail_delete_group_sub: 'Supprimer définitivement pour tous',
    detail_delete_group_title: 'Supprimer le groupe ?',
    detail_delete_group_msg: 'Cela supprimera définitivement le groupe et tous ses messages. Cette action est irréversible.',
    detail_delete_group_btn: 'Supprimer le groupe',
    detail_no_friends_add: 'Tous vos contacts sont déjà dans le groupe.',
    detail_save_changes: 'Enregistrer',
    detail_group_image_label: 'AVATAR DU GROUPE',
    detail_upload_image: 'Télécharger une image',
    wb_title: 'Tableau blanc',
    wb_clear_title: 'Effacer le tableau',
    wb_clear_msg: 'Supprimer tous les traits ? Cette action est irréversible.',
    wb_clear_btn: 'Effacer',
    wb_pen: 'Crayon',
    wb_eraser: 'Gomme',
    wb_opacity: 'Opacité',
    profile_blocked_title: 'Utilisateurs bloqués',
    profile_blocked_count_one: 'compte bloqué',
    profile_blocked_count_many: 'comptes bloqués',
    profile_blocked_empty: 'Aucun compte bloqué',
    profile_blocked_search: "Rechercher par nom d'utilisateur...",
    profile_blocked_unblock: 'Débloquer',
    create_group_title: 'Nouveau Groupe',
    create_group_tag: 'Construis ton Cercle',
    create_group_heading_pre: 'Créer un',
    create_group_heading_accent: 'groupe',
    create_group_heading_post: 'de chat',
    create_group_preview_placeholder: 'Nom du groupe…',
    create_group_preview_members_one: 'membre sélectionné',
    create_group_preview_members_many: 'membres sélectionnés',
    create_group_preview_empty: 'Aucun membre encore',
    create_group_name_label: 'Nom du groupe',
    create_group_name_placeholder: 'Tapez un nom…',
    create_group_color_label: 'Couleur du groupe',
    create_group_members_label: 'Ajouter des membres',
    create_group_loading: 'Chargement des contacts…',
    create_group_no_contacts: 'Aucun contact à ajouter',
    create_group_btn: 'Créer le Groupe',
    create_group_error: 'Impossible de créer le groupe. Veuillez réessayer.',
    req_title: 'Demandes d\'Amis',
    req_tag: 'Nouvelles Connexions',
    req_heading_pre: 'Qui veut se',
    req_heading_accent: 'connecter',
    req_heading_post: 'avec toi ?',
    req_loading: 'Chargement des demandes…',
    req_empty: 'Aucune demande en attente',
    req_accept: 'Accepter',
    req_decline: 'Refuser',
    add_title: 'Ajouter un Contact',
    add_hero_pre: 'Retrouve tes',
    add_hero_accent: 'amis.',
    add_hero_sub: 'Recherche par nom d\'utilisateur pour démarrer un chat.',
    add_placeholder: 'Rechercher par nom ou utilisateur',
    add_hint_title: 'Commence à écrire pour chercher',
    add_hint_sub: 'Tape au moins 2 caractères pour trouver des utilisateurs.',
    add_no_results: 'Aucun utilisateur trouvé pour',
  },
  de: {
    nav_contacts: 'Start',
    nav_new_group: 'Neue Gruppe',
    nav_requests: 'Anfragen',
    nav_profile: 'Profil',
    status_title: 'MEIN STATUS',
    status_online: 'Online',
    status_away: 'Abwesend',
    status_busy: 'Beschäftigt',
    status_offline: 'Offline',
    home_search_contacts: 'Kontakte suchen...',
    home_search_groups: 'Gruppen suchen...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Gruppen',
    home_promo_title: 'Starte etwas Neues',
    home_promo_desc: 'Koordiniere deine Wochenendpläne in einem neuen Gruppen-Chat.',
    home_promo_btn: 'Gruppe erstellen',
    home_my_groups: 'Meine Gruppen',
    settings_title: 'Einstellungen',
    settings_notifications: 'Benachrichtigungen',
    settings_sound: 'Ton',
    settings_sound_sub: 'Ton für eingehende Nachrichten abspielen',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Haptisches Feedback bei Benachrichtigungen',
    settings_appearance: 'Darstellung',
    settings_theme: 'Design',
    settings_theme_light: 'Hell',
    settings_theme_dark: 'Dunkel',
    settings_language: 'Sprache',
    settings_language_desc: 'Wähle deine bevorzugte Sprache für die Benutzeroberfläche.',
    settings_edit_profile: 'Profil bearbeiten',
    profile_title: 'Profil',
    profile_edit_title: 'Profil bearbeiten',
    profile_full_name: 'Vollständiger Name',
    profile_username: 'Benutzername',
    profile_status: 'Status',
    profile_change_photo: 'Profilbild ändern',
    profile_username_hint: 'Benutzernamen werden verifiziert und können nicht geändert werden.',
    profile_custom_status: 'BENUTZERDEFINIERTER STATUS',
    profile_set_status: 'Status setzen…',
    profile_whats_status: 'Was ist dein Status?',
    profile_your_name: 'Dein Name',
    profile_save: 'Änderungen speichern',
    profile_logout: 'Abmelden',
    chat_private_photo: 'Privates Foto',
    chat_image_seen: 'Bild gesehen',
    chat_open_image: 'Bild öffnen',
    chat_image_deleted: 'Bild gelöscht',
    chat_image: 'Bild',
    chat_me: 'Ich',
    chat_member: 'Mitglied',
    chat_members: 'Mitglieder',
    chat_caption: 'Bildunterschrift hinzufügen...',
    chat_type: 'Nachricht eingeben...',
    chat_image_count_one: 'Bild',
    chat_image_count_many: 'Bilder',
    chat_is_writing: 'schreibt...',
    chat_date_today: 'Heute',
    chat_date_yesterday: 'Gestern',
    chat_edit: 'Bearbeiten',
    chat_delete: 'Löschen',
    chat_save: 'Speichern',
    chat_cancel: 'Abbrechen',
    chat_edited: 'bearbeitet',
    chat_msg_deleted: 'Diese Nachricht wurde gelöscht',
    buzz_toast: 'hat dich gebuzzt!',
    settings_buzz: 'Buzz',
    settings_buzz_sub: 'Klassischer Messenger-Buzz',
    settings_buzz_custom: 'Eigener Sound',
    settings_buzz_default: 'Standardsound',
    notif_view: 'Ansehen',
    auth_email_label: 'E-Mail-Adresse',
    auth_password_label: 'Passwort',
    auth_sign_in: 'Anmelden',
    auth_back_signin: 'Zurück zur Anmeldung',
    auth_login_title: 'Willkommen zurück',
    auth_remember_me: 'Angemeldet bleiben',
    auth_forgot_password: 'Passwort vergessen?',
    auth_no_account: 'Noch kein Konto?',
    auth_create_account: 'Neues Konto erstellen',
    auth_register_hero: 'Tritt dem',
    auth_register_hero_accent: 'Spielplatz bei.',
    auth_register_sub: 'Erlebe die Wärme der Verbindung der frühen 2000er, neu gedacht für die moderne Ära.',
    auth_create_account_title: 'Konto erstellen',
    auth_full_name: 'Vollständiger Name',
    auth_username: 'Benutzername',
    auth_dob: 'Geburtsdatum',
    auth_confirm_password: 'Passwort bestätigen',
    auth_register_btn: 'Konto registrieren',
    auth_already_account: 'Bereits ein Konto?',
    auth_recovery_tag: 'Kontowiederherstellung',
    auth_forgot_hero: 'Passwort',
    auth_forgot_hero_accent: 'vergessen?',
    auth_forgot_sub: 'Gib deine E-Mail ein und wir senden dir einen Reset-Link.',
    auth_send_reset: 'Reset-Link senden',
    auth_check_inbox: 'Prüfe dein Postfach',
    auth_reset_sent_pre: 'Wir haben einen Reset-Link gesendet an',
    auth_reset_sent_post: 'Folge dem Link, um ein neues Passwort festzulegen.',
    auth_spam_hint: 'Nicht gefunden? Prüfe deinen Spam-Ordner.',
    auth_security_tag: 'Sicherheit',
    auth_reset_hero: 'Neues',
    auth_reset_hero_accent: 'Passwort festlegen',
    auth_reset_sub: 'Gib dein neues Passwort ein und bestätige es.',
    auth_new_password_placeholder: 'Neues Passwort',
    auth_confirm_password_placeholder: 'Passwort bestätigen',
    auth_save_password: 'Neues Passwort speichern',
    auth_all_done: 'Fertig!',
    auth_password_updated: 'Dein Passwort wurde aktualisiert. Du kannst dich jetzt mit deinen neuen Zugangsdaten anmelden.',
    auth_err_name_required: 'Name ist erforderlich',
    auth_err_dob_required: 'Geburtsdatum ist erforderlich',
    auth_err_username_required: 'Benutzername ist erforderlich',
    auth_err_username_min: 'Mindestens 3 Zeichen',
    auth_err_email_required: 'E-Mail ist erforderlich',
    auth_err_email_invalid: 'Ungültige E-Mail',
    auth_err_email_enter: 'Gib deine E-Mail ein',
    auth_err_email_taken: 'Diese E-Mail ist bereits registriert',
    auth_err_password_required: 'Passwort ist erforderlich',
    auth_err_password_min: 'Mindestens 6 Zeichen',
    auth_err_password_enter: 'Passwort eingeben',
    auth_pwd_rule_length:  'Mindestens 8 Zeichen',
    auth_pwd_rule_upper:   'Ein Großbuchstabe (A–Z)',
    auth_pwd_rule_lower:   'Ein Kleinbuchstabe (a–z)',
    auth_pwd_rule_number:  'Eine Zahl (0–9)',
    auth_pwd_rule_special: 'Ein Sonderzeichen (!@#$…)',
    auth_err_password_weak: 'Das Passwort erfüllt nicht alle Anforderungen',
    auth_err_confirm_required: 'Bestätige dein Passwort',
    auth_err_passwords_mismatch: 'Passwörter stimmen nicht überein',
    auth_err_generic: 'Ein Fehler ist aufgetreten. Bitte versuche es erneut.',
    auth_err_link_expired: 'Fehler beim Aktualisieren. Der Link ist möglicherweise abgelaufen.',
    auth_strength_weak: 'Schwach',
    auth_strength_medium: 'Mittel',
    auth_strength_strong: 'Stark',
    detail_title: 'Details',
    detail_members: 'Mitglieder',
    detail_see_all: 'Alle anzeigen',
    detail_add: 'Hinzufügen',
    detail_mute: 'Stummschalten',
    detail_no_members: 'Keine Mitglieder gefunden',
    detail_danger_zone: 'Gefahrenzone',
    detail_leave_group: 'Gruppe verlassen',
    detail_leave_group_sub: 'Diese Gruppenunterhaltung verlassen',
    detail_audio: 'Audio',
    detail_video: 'Video',
    detail_privacy: 'Datenschutz & Einstellungen',
    detail_mute_notifications: 'Benachrichtigungen stummschalten',
    detail_mute_sub: 'Nachrichten von diesem Kontakt stummschalten',
    detail_shared_media: 'Geteilte Medien',
    detail_shared_media_sub: 'Fotos, Videos und Dokumente',
    detail_no_media: 'Noch keine geteilten Medien',
    detail_download: 'Herunterladen',
    detail_mg_today: 'Heute',
    detail_mg_yesterday: 'Gestern',
    detail_mg_this_week: 'Diese Woche',
    detail_mg_this_month: 'Diesen Monat',
    detail_mg_this_year: 'Dieses Jahr',
    detail_mg_past_years: 'Älter',
    detail_block: 'Kontakt blockieren',
    detail_block_sub: 'Nachrichten und Anrufe verhindern',
    detail_block_confirm_msg: 'Dieser Nutzer kann dich nicht mehr finden oder dir Nachrichten senden.',
    detail_block_done: 'Blockiert',
    detail_delete_friendship: 'Freundschaft löschen',
    detail_delete_sub: 'Aus deiner Kontaktliste entfernen',
    detail_delete_confirm_msg: 'Dieser Kontakt wird aus beiden Kontaktlisten entfernt.',
    detail_delete_btn: 'Löschen',
    detail_role_owner: 'Inhaber',
    detail_role_admin: 'Admin',
    detail_edit_group: 'Gruppe bearbeiten',
    detail_edit_name_placeholder: 'Gruppenname',
    detail_add_member: 'Mitglied hinzufügen',
    detail_remove_member: 'Aus Gruppe entfernen',
    detail_promote_admin: 'Zum Admin befördern',
    detail_demote_admin: 'Admin-Rolle entfernen',
    detail_remove_confirm_title: 'Mitglied entfernen?',
    detail_remove_confirm_msg: 'Dieses Mitglied wird aus der Gruppe entfernt.',
    detail_remove_btn: 'Entfernen',
    detail_leave_confirm_title: 'Gruppe verlassen?',
    detail_leave_confirm_msg: 'Du wirst keinen Zugriff mehr auf diese Gruppe haben.',
    detail_leave_btn: 'Verlassen',
    detail_owner_leave_title: 'Eigentümerschaft übertragen',
    detail_owner_leave_msg: 'Wähle ein Mitglied als neuen Inhaber, bevor du die Gruppe verlässt.',
    detail_transfer_btn: 'Übertragen & verlassen',
    detail_delete_group: 'Gruppe löschen',
    detail_delete_group_sub: 'Für alle endgültig löschen',
    detail_delete_group_title: 'Gruppe löschen?',
    detail_delete_group_msg: 'Dies löscht die Gruppe und alle Nachrichten dauerhaft. Dies kann nicht rückgängig gemacht werden.',
    detail_delete_group_btn: 'Gruppe löschen',
    detail_no_friends_add: 'Alle deine Kontakte sind bereits in der Gruppe.',
    detail_save_changes: 'Speichern',
    detail_group_image_label: 'GRUPPEN-AVATAR',
    detail_upload_image: 'Bild hochladen',
    wb_title: 'Whiteboard',
    wb_clear_title: 'Whiteboard leeren',
    wb_clear_msg: 'Alle Striche löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
    wb_clear_btn: 'Leeren',
    wb_pen: 'Stift',
    wb_eraser: 'Radiergummi',
    wb_opacity: 'Deckkraft',
    profile_blocked_title: 'Gesperrte Nutzer',
    profile_blocked_count_one: 'gesperrtes Konto',
    profile_blocked_count_many: 'gesperrte Konten',
    profile_blocked_empty: 'Keine gesperrten Konten',
    profile_blocked_search: 'Nach Benutzername suchen...',
    profile_blocked_unblock: 'Entsperren',
    create_group_title: 'Neue Gruppe',
    create_group_tag: 'Bau deinen Kreis',
    create_group_heading_pre: 'Erstelle einen',
    create_group_heading_accent: 'Gruppen',
    create_group_heading_post: 'chat',
    create_group_preview_placeholder: 'Gruppenname…',
    create_group_preview_members_one: 'Mitglied ausgewählt',
    create_group_preview_members_many: 'Mitglieder ausgewählt',
    create_group_preview_empty: 'Noch keine Mitglieder',
    create_group_name_label: 'Gruppenname',
    create_group_name_placeholder: 'Namen eingeben…',
    create_group_color_label: 'Gruppenfarbe',
    create_group_members_label: 'Mitglieder hinzufügen',
    create_group_loading: 'Kontakte werden geladen…',
    create_group_no_contacts: 'Keine Kontakte zum Hinzufügen',
    create_group_btn: 'Gruppe erstellen',
    create_group_error: 'Gruppe konnte nicht erstellt werden. Bitte erneut versuchen.',
    req_title: 'Freundschaftsanfragen',
    req_tag: 'Neue Verbindungen',
    req_heading_pre: 'Wer möchte sich mit',
    req_heading_accent: 'dir',
    req_heading_post: 'verbinden?',
    req_loading: 'Anfragen werden geladen…',
    req_empty: 'Keine ausstehenden Anfragen',
    req_accept: 'Annehmen',
    req_decline: 'Ablehnen',
    add_title: 'Kontakt hinzufügen',
    add_hero_pre: 'Finde deine',
    add_hero_accent: 'Freunde.',
    add_hero_sub: 'Suche nach Benutzername, um einen Chat zu starten.',
    add_placeholder: 'Nach Name oder Benutzer suchen',
    add_hint_title: 'Tippe um zu suchen',
    add_hint_sub: 'Mindestens 2 Zeichen eingeben, um Nutzer zu finden.',
    add_no_results: 'Keine Nutzer gefunden für',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {

  private _lang: Lang = 'en';

  constructor() {
    const saved = localStorage.getItem('appLang') as Lang;
    if (saved && T[saved]) this._lang = saved;
  }

  get lang(): Lang { return this._lang; }

  setLanguage(lang: Lang) {
    if (!T[lang]) return;
    this._lang = lang;
    localStorage.setItem('appLang', lang);
  }

  t(key: string): string {
    return T[this._lang][key] ?? T['en'][key] ?? key;
  }
}
