import { Injectable } from '@angular/core';

export type Lang = 'en' | 'es' | 'fr' | 'de';

const T: Record<Lang, Record<string, string>> = {
  en: {
    // Navigation
    nav_contacts: 'Contacts',
    nav_new_group: 'New Group',
    nav_requests: 'Requests',
    nav_profile: 'Profile',
    // Status
    status_title: 'MY STATUS',
    status_online: 'Online',
    status_away: 'Away',
    status_busy: 'Busy',
    status_offline: 'Offline',
    // Home
    home_search_contacts: 'Search contacts...',
    home_search_groups: 'Search groups...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Groups',
    home_promo_title: 'Start something new',
    home_promo_desc: 'Coordinate your weekend plans in a new group chat.',
    home_promo_btn: 'Create Group',
    home_my_groups: 'My groups',
    // Settings
    settings_title: 'Settings',
    settings_notifications: 'Notifications',
    settings_sound: 'Sound',
    settings_sound_sub: 'Play sound for incoming messages',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Haptic feedback on alerts',
    settings_appearance: 'Appearance',
    settings_theme: 'Theme',
    settings_theme_light: 'Light',
    settings_language: 'Language',
    settings_language_desc: 'Choose your preferred language for the interface.',
    settings_edit_profile: 'Edit Profile',
    // Profile
    profile_title: 'Profile',
    profile_edit_title: 'Edit Profile',
    profile_full_name: 'Full Name',
    profile_username: 'Username',
    profile_status: 'Status',
    profile_change_photo: 'Change profile picture',
    profile_username_hint: 'Usernames are verified and cannot be changed.',
    profile_custom_status: 'CUSTOM STATUS',
    profile_set_status: 'Set a status…',
    profile_whats_status: "What's your status?",
    profile_your_name: 'Your name',
    profile_save: 'Save Changes',
    profile_logout: 'Log Out',
    // Chat
    chat_private_photo: 'Private photo',
    chat_image_seen: 'Image seen',
    chat_open_image: 'Open image',
    chat_image_deleted: 'Image deleted',
    chat_image: 'Image',
    chat_me: 'Me',
    chat_member: 'Member',
    chat_members: 'members',
    chat_caption: 'Add a caption...',
    chat_type: 'Type a message...',
    chat_image_count_one: 'image',
    chat_image_count_many: 'images',
    chat_is_writing: 'is writing...',
    chat_date_today: 'Today',
    chat_date_yesterday: 'Yesterday',
    // Detail pages
    detail_title: 'Details',
    detail_members: 'Members',
    detail_see_all: 'See All',
    detail_add: 'Add',
    detail_mute: 'Mute',
    detail_no_members: 'No members found',
    detail_danger_zone: 'Danger Zone',
    detail_leave_group: 'Leave Group',
    detail_leave_group_sub: 'Exit this community conversation',
    detail_audio: 'Audio',
    detail_video: 'Video',
    detail_privacy: 'Privacy & Preferences',
    detail_mute_notifications: 'Mute Notifications',
    detail_mute_sub: 'Silence messages from this contact',
    detail_shared_media: 'Shared Media',
    detail_shared_media_sub: 'Photos, videos and documents',
    detail_block: 'Block Contact',
    detail_block_sub: 'Prevent messages and calls',
    detail_delete_friendship: 'Delete Friendship',
    detail_delete_sub: 'Remove from your contact list',
  },
  es: {
    nav_contacts: 'Contactos',
    nav_new_group: 'Nuevo Grupo',
    nav_requests: 'Solicitudes',
    nav_profile: 'Perfil',
    status_title: 'MI ESTADO',
    status_online: 'En línea',
    status_away: 'Ausente',
    status_busy: 'Ocupado',
    status_offline: 'Desconectado',
    home_search_contacts: 'Buscar contactos...',
    home_search_groups: 'Buscar grupos...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Grupos',
    home_promo_title: 'Empieza algo nuevo',
    home_promo_desc: 'Organiza los planes del fin de semana en un nuevo chat grupal.',
    home_promo_btn: 'Crear Grupo',
    home_my_groups: 'Mis grupos',
    settings_title: 'Ajustes',
    settings_notifications: 'Notificaciones',
    settings_sound: 'Sonido',
    settings_sound_sub: 'Reproducir sonido con mensajes entrantes',
    settings_vibration: 'Vibración',
    settings_vibration_sub: 'Vibración táctil en alertas',
    settings_appearance: 'Apariencia',
    settings_theme: 'Tema',
    settings_theme_light: 'Claro',
    settings_language: 'Idioma',
    settings_language_desc: 'Elige tu idioma preferido para la interfaz.',
    settings_edit_profile: 'Editar Perfil',
    profile_title: 'Perfil',
    profile_edit_title: 'Editar Perfil',
    profile_full_name: 'Nombre Completo',
    profile_username: 'Usuario',
    profile_status: 'Estado',
    profile_change_photo: 'Cambiar foto de perfil',
    profile_username_hint: 'Los nombres de usuario son verificados y no se pueden cambiar.',
    profile_custom_status: 'ESTADO PERSONALIZADO',
    profile_set_status: 'Establece un estado…',
    profile_whats_status: '¿Cuál es tu estado?',
    profile_your_name: 'Tu nombre',
    profile_save: 'Guardar Cambios',
    profile_logout: 'Cerrar Sesión',
    chat_private_photo: 'Foto privada',
    chat_image_seen: 'Imagen vista',
    chat_open_image: 'Abrir imagen',
    chat_image_deleted: 'Imagen eliminada',
    chat_image: 'Imagen',
    chat_me: 'Yo',
    chat_member: 'Miembro',
    chat_members: 'miembros',
    chat_caption: 'Añade un pie de foto...',
    chat_type: 'Escribe un mensaje...',
    chat_image_count_one: 'imagen',
    chat_image_count_many: 'imágenes',
    chat_is_writing: 'está escribiendo...',
    chat_date_today: 'Hoy',
    chat_date_yesterday: 'Ayer',
    detail_title: 'Detalles',
    detail_members: 'Miembros',
    detail_see_all: 'Ver todos',
    detail_add: 'Añadir',
    detail_mute: 'Silenciar',
    detail_no_members: 'No se encontraron miembros',
    detail_danger_zone: 'Zona de peligro',
    detail_leave_group: 'Salir del grupo',
    detail_leave_group_sub: 'Abandonar esta conversación',
    detail_audio: 'Audio',
    detail_video: 'Vídeo',
    detail_privacy: 'Privacidad y Preferencias',
    detail_mute_notifications: 'Silenciar notificaciones',
    detail_mute_sub: 'Silenciar mensajes de este contacto',
    detail_shared_media: 'Medios compartidos',
    detail_shared_media_sub: 'Fotos, vídeos y documentos',
    detail_block: 'Bloquear contacto',
    detail_block_sub: 'Evitar mensajes y llamadas',
    detail_delete_friendship: 'Eliminar amistad',
    detail_delete_sub: 'Eliminar de tu lista de contactos',
  },
  fr: {
    nav_contacts: 'Contacts',
    nav_new_group: 'Nouveau Groupe',
    nav_requests: 'Demandes',
    nav_profile: 'Profil',
    status_title: 'MON STATUT',
    status_online: 'En ligne',
    status_away: 'Absent',
    status_busy: 'Occupé',
    status_offline: 'Hors ligne',
    home_search_contacts: 'Rechercher des contacts...',
    home_search_groups: 'Rechercher des groupes...',
    home_tab_chats: 'Discussions',
    home_tab_groups: 'Groupes',
    home_promo_title: 'Commencez quelque chose',
    home_promo_desc: 'Organisez vos plans de week-end dans un nouveau chat de groupe.',
    home_promo_btn: 'Créer un Groupe',
    home_my_groups: 'Mes groupes',
    settings_title: 'Paramètres',
    settings_notifications: 'Notifications',
    settings_sound: 'Son',
    settings_sound_sub: 'Jouer un son pour les messages entrants',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Retour haptique sur les alertes',
    settings_appearance: 'Apparence',
    settings_theme: 'Thème',
    settings_theme_light: 'Clair',
    settings_language: 'Langue',
    settings_language_desc: "Choisissez votre langue préférée pour l'interface.",
    settings_edit_profile: 'Modifier le Profil',
    profile_title: 'Profil',
    profile_edit_title: 'Modifier le Profil',
    profile_full_name: 'Nom Complet',
    profile_username: "Nom d'utilisateur",
    profile_status: 'Statut',
    profile_change_photo: 'Changer la photo de profil',
    profile_username_hint: "Les noms d'utilisateur sont vérifiés et ne peuvent pas être modifiés.",
    profile_custom_status: 'STATUT PERSONNALISÉ',
    profile_set_status: 'Définir un statut…',
    profile_whats_status: 'Quel est votre statut?',
    profile_your_name: 'Votre nom',
    profile_save: 'Enregistrer',
    profile_logout: 'Se Déconnecter',
    chat_private_photo: 'Photo privée',
    chat_image_seen: 'Image vue',
    chat_open_image: "Ouvrir l'image",
    chat_image_deleted: 'Image supprimée',
    chat_image: 'Image',
    chat_me: 'Moi',
    chat_member: 'Membre',
    chat_members: 'membres',
    chat_caption: 'Ajouter une légende...',
    chat_type: 'Tapez un message...',
    chat_image_count_one: 'image',
    chat_image_count_many: 'images',
    chat_is_writing: 'est en train d\'écrire...',
    chat_date_today: "Aujourd'hui",
    chat_date_yesterday: 'Hier',
    detail_title: 'Détails',
    detail_members: 'Membres',
    detail_see_all: 'Voir tout',
    detail_add: 'Ajouter',
    detail_mute: 'Muet',
    detail_no_members: 'Aucun membre trouvé',
    detail_danger_zone: 'Zone dangereuse',
    detail_leave_group: 'Quitter le groupe',
    detail_leave_group_sub: 'Quitter cette conversation',
    detail_audio: 'Audio',
    detail_video: 'Vidéo',
    detail_privacy: 'Confidentialité & Préférences',
    detail_mute_notifications: 'Désactiver les notifications',
    detail_mute_sub: 'Masquer les messages de ce contact',
    detail_shared_media: 'Médias partagés',
    detail_shared_media_sub: 'Photos, vidéos et documents',
    detail_block: 'Bloquer le contact',
    detail_block_sub: 'Empêcher les messages et appels',
    detail_delete_friendship: 'Supprimer l\'amitié',
    detail_delete_sub: 'Retirer de votre liste de contacts',
  },
  de: {
    nav_contacts: 'Kontakte',
    nav_new_group: 'Neue Gruppe',
    nav_requests: 'Anfragen',
    nav_profile: 'Profil',
    status_title: 'MEIN STATUS',
    status_online: 'Online',
    status_away: 'Abwesend',
    status_busy: 'Beschäftigt',
    status_offline: 'Offline',
    home_search_contacts: 'Kontakte suchen...',
    home_search_groups: 'Gruppen suchen...',
    home_tab_chats: 'Chats',
    home_tab_groups: 'Gruppen',
    home_promo_title: 'Starte etwas Neues',
    home_promo_desc: 'Koordiniere deine Wochenendpläne in einem neuen Gruppen-Chat.',
    home_promo_btn: 'Gruppe erstellen',
    home_my_groups: 'Meine Gruppen',
    settings_title: 'Einstellungen',
    settings_notifications: 'Benachrichtigungen',
    settings_sound: 'Ton',
    settings_sound_sub: 'Ton für eingehende Nachrichten abspielen',
    settings_vibration: 'Vibration',
    settings_vibration_sub: 'Haptisches Feedback bei Benachrichtigungen',
    settings_appearance: 'Darstellung',
    settings_theme: 'Design',
    settings_theme_light: 'Hell',
    settings_language: 'Sprache',
    settings_language_desc: 'Wähle deine bevorzugte Sprache für die Benutzeroberfläche.',
    settings_edit_profile: 'Profil bearbeiten',
    profile_title: 'Profil',
    profile_edit_title: 'Profil bearbeiten',
    profile_full_name: 'Vollständiger Name',
    profile_username: 'Benutzername',
    profile_status: 'Status',
    profile_change_photo: 'Profilbild ändern',
    profile_username_hint: 'Benutzernamen werden verifiziert und können nicht geändert werden.',
    profile_custom_status: 'BENUTZERDEFINIERTER STATUS',
    profile_set_status: 'Status setzen…',
    profile_whats_status: 'Was ist dein Status?',
    profile_your_name: 'Dein Name',
    profile_save: 'Änderungen speichern',
    profile_logout: 'Abmelden',
    chat_private_photo: 'Privates Foto',
    chat_image_seen: 'Bild gesehen',
    chat_open_image: 'Bild öffnen',
    chat_image_deleted: 'Bild gelöscht',
    chat_image: 'Bild',
    chat_me: 'Ich',
    chat_member: 'Mitglied',
    chat_members: 'Mitglieder',
    chat_caption: 'Bildunterschrift hinzufügen...',
    chat_type: 'Nachricht eingeben...',
    chat_image_count_one: 'Bild',
    chat_image_count_many: 'Bilder',
    chat_is_writing: 'schreibt...',
    chat_date_today: 'Heute',
    chat_date_yesterday: 'Gestern',
    detail_title: 'Details',
    detail_members: 'Mitglieder',
    detail_see_all: 'Alle anzeigen',
    detail_add: 'Hinzufügen',
    detail_mute: 'Stummschalten',
    detail_no_members: 'Keine Mitglieder gefunden',
    detail_danger_zone: 'Gefahrenzone',
    detail_leave_group: 'Gruppe verlassen',
    detail_leave_group_sub: 'Diese Gruppenunterhaltung verlassen',
    detail_audio: 'Audio',
    detail_video: 'Video',
    detail_privacy: 'Datenschutz & Einstellungen',
    detail_mute_notifications: 'Benachrichtigungen stummschalten',
    detail_mute_sub: 'Nachrichten von diesem Kontakt stummschalten',
    detail_shared_media: 'Geteilte Medien',
    detail_shared_media_sub: 'Fotos, Videos und Dokumente',
    detail_block: 'Kontakt blockieren',
    detail_block_sub: 'Nachrichten und Anrufe verhindern',
    detail_delete_friendship: 'Freundschaft löschen',
    detail_delete_sub: 'Aus deiner Kontaktliste entfernen',
  },
};

@Injectable({ providedIn: 'root' })
export class LanguageService {

  private _lang: Lang = 'en';

  constructor() {
    const saved = localStorage.getItem('appLang') as Lang;
    if (saved && T[saved]) this._lang = saved;
  }

  get lang(): Lang { return this._lang; }

  setLanguage(lang: Lang) {
    if (!T[lang]) return;
    this._lang = lang;
    localStorage.setItem('appLang', lang);
  }

  t(key: string): string {
    return T[this._lang][key] ?? T['en'][key] ?? key;
  }
}
